spring.datasource.url=jdbc:mysql://localhost:3306/MakeMyTrip
spring.datasource.username=root
spring.datasource.password=Sunflower427#$
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8090
jwt.secret=tripweaver_secret_key
jwt.expiration=86400000
spring.main.allow-bean-definition-overriding=true

geoapify.api.key=67ab99d0b36e4f6c95c9da815312c1f8
aviationstack.api.key=b5b4e4f91ff79b779b084dd2f38e3073
google.places.api.key=AIzaSyAoOXCKnTd70n9LvzbgU7SMG6eHibF36pI
openai.api.key=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
gemini.api.key=AIzaSyCZna3rx6QVhLXzaps86aElLJJ-OIAqpSg
amadeus.api.key=lSc3RzXkkApmaSldIInE1GahFXEDb2vw
amadeus.api.secret=ZSa8oPXZvjREsAHw
